apiVersion: v1
kind: Service
metadata:
  name: hello-world-svc
spec:
  selector:
    app: helloworld
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30002
    protocol: TCP
