apiVersion: v1
kind: ReplicationController
metadata: 
  name: helloworld-rc
spec:
  replicas: 2
  selector:
    app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: vsuryateja/hello-world:1-0-0-SNAPSHOT
        ports:
        - containerPort: 8080
