apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world-deploy
spec:
  replicas: 2
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: vsuryateja/openmrs:2.1.3
        ports:
        - containerPort: 8080

